name: order_market_app
description: 식자재 주문 마켓 앱 - 디지털화된 식자재 주문 시스템
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.7.2
  
  # Firebase - 최신 버전 (iOS 18 호환성 개선)
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  # firebase_storage: ^12.4.8  # 임시 주석 처리 - Swift 6.0 Sendable 오류
  
  # Local Storage
  shared_preferences: ^2.5.2
  
  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.5.1
  table_calendar: ^3.0.9
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Image & File handling
  image_picker: ^1.0.4
  retry: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env
    - assets/icons/
