// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeYdzJbILRBrxAlgp_kkGF5RDfZeb-lk',
    appId: '1:486521508162:android:602bb63397cc90b28a38db',
    messagingSenderId: '486521508162',
    projectId: 'order-market-app',
    storageBucket: 'order-market-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-TtpLTSgTJzICfp-MqOhlPakRNhrHtEw',
    appId: '1:486521508162:web:4ddd0f9d9e6b27668a38db',
    messagingSenderId: '486521508162',
    projectId: 'order-market-app',
    authDomain: 'order-market-app.firebaseapp.com',
    storageBucket: 'order-market-app.firebasestorage.app',
    measurementId: 'G-TX7LR7T93F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiZj_AEkgZvhOvg08Q2MjQiL1EAWrolHk',
    appId: '1:486521508162:ios:7585660b1ee9be578a38db',
    messagingSenderId: '486521508162',
    projectId: 'order-market-app',
    storageBucket: 'order-market-app.firebasestorage.app',
    iosClientId: '486521508162-dk6fl36gehkba8gepdnpbakl28uadeec.apps.googleusercontent.com',
    iosBundleId: 'com.company.ordermarket',
  );

}